In [13]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [19]:
print(a[1:4])
print(a[4:])
print(a[:4])

[2 3 4]
[5]
[1 2 3 4]


In [25]:
#Exclude perticular elemsnts in array sequence
print(a[0:5:2])
print(a[::3]) #from start to end removing 2 and 3rd element

[1 3 5]
[1 4]


In [28]:
#slicing in 2d array
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [29]:
#slicing rows
print(a[1,1:3])

[7 8]


In [30]:
#slicing coulumns
print(a[:,1:3])

[[2 3]
 [7 8]]
